version: '3'

volumes:
  neo4j_data:
  neo4j_import:
  neo4j_plugins:

services:
  neo4j:
#    build: .
    image: neo4j:latest 
    container_name: neo4j
    restart: always
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_AUTH: neo4j/test
    volumes:
      - neo4j_data:/data
      - neo4j_import:/var/lib/neo4j/import
      - neo4j_plugins:/plugins
