version: '3'

volumes:
  neo4j-data:
  neo4j-import:
  neo4j-plugins:
  neo4j-logs:

services:
  neo4j:
    image: neo4j:latest 
    container_name: "neo4j"
    hostname: neo4j
    restart: always
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/test
    volumes:
      - neo4j-data:/data
      - neo4j-logs:/logs
      - neo4j-import:/var/lib/neo4j/import
      - neo4j-plugins:/plugins
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      - MONGO_INITDB_DATABASE=docsdb
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootPassword
    ports:
     - 2017-2019:2017-2019